services:
  database:
    image: postgres:16-alpine
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=note_manager
    volumes:
      - postgres-data:/var/lib/postgresql/data

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - ./keycloak/.env
    depends_on:
      - database
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - ./backend/.env.prod
    depends_on:
      - keycloak
    ports:
      - "8000:8000"

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - backend

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "4000:3000"
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres-data:
  grafana-storage:
