{
 "title": "FastAPI Dashboard",
 "time": { "from": "2024-06-22T10:16:08.757Z", "to": "2024-06-22T10:26:27.320Z" },
 "panels": [
  {
   "title": "Requests total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 0 },
   "targets": [
    { "expr": "http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request per minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Requests under 100ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_bucket{le=\"0.1\"}[1m]) \n/ ignoring (le) increase(http_request_duration_seconds_count[1m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Memory usage (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 11 },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}