apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config-map
data:
  KC_DB: postgres
  KC_HOSTNAME: localhost
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_HTTP_ENABLED: "true"
